# Generated by Django 3.2.25 on 2024-12-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='reference_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='reference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
