# Generated by Django 3.2.25 on 2024-12-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20241204_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='reference_id',
            new_name='id',
        ),
    ]
