# Generated by Django 3.2.25 on 2025-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='references',
            field=models.ManyToManyField(related_name='groups', to='references.Reference'),
        ),
    ]
