# Generated by Django 3.2.25 on 2024-11-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reference_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_images', to='reference_images.referenceimage')),
            ],
        ),
    ]
