# Generated by Django 3.2.25 on 2024-12-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
