# Generated by Django 3.2.25 on 2024-12-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon_url',
        ),
    ]
