# Generated by Django 3.2.25 on 2024-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241204_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon_url',
            field=models.URLField(blank=True, default='/icons/icon-1.png', null=True),
        ),
    ]
